import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'providers.dart';

class AppLocalizations {
  static const fallbackLocale = 'en';

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'appName': 'MediGuide AI',
      'appTagline': 'Your intelligent health companion',
      'loadingProfile': 'Loading your health profile...',
      'loading': 'Loading...',
      'skip': 'Skip',
      'next': 'Next',
      'getStarted': 'Get Started',
      'home': 'Home',
      'symptoms': 'Symptoms',
      'medicines': 'Medicines',
      'nearby': 'Nearby',
      'profile': 'Profile',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'signInWithGoogle': 'Continue with Google',
      'fullName': 'Full Name',
      'email': 'Email',
      'password': 'Password',
      'welcomeBack': 'Welcome back',
      'createAccount': 'Create account',
      'signInSubtitle': 'Sign in to continue your health journey.',
      'signUpSubtitle':
          'Create your account and start tracking your health safely.',
      'orContinueWith': 'or continue with',
      'invalidEmailAddress': 'Please enter a valid email address.',
      'minimumPasswordLength': 'Minimum 6 characters.',
      'authFailed': 'Authentication failed.',
      'googleSignInFailed': 'Google sign-in failed.',
      'checkingFirebaseSetup': 'Checking Firebase setup',
      'checkingFirebaseSetupSubtitle':
          'Verifying Authentication and project configuration before sign-in.',
      'firebaseSetupRequired': 'Firebase Authentication needs setup',
      'firebaseSetupRequiredSubtitle':
          'This project currently returns CONFIGURATION_NOT_FOUND. Enable Firebase Authentication, turn on Email/Password and Google, add Android SHA keys, then download a new google-services.json.',
      'firebaseSetupNetworkIssue': 'Unable to verify Firebase setup',
      'firebaseSetupNetworkIssueSubtitle':
          'We could not check Firebase Authentication right now. Verify your internet connection and try again.',
      'retryConfigurationCheck': 'Retry Check',
      'previewModeTitle': 'Open the interface in preview',
      'previewModeSubtitle':
          'Use local sample data to access the dashboard, cards, and nearby medical map while Firebase or Google APIs are unavailable.',
      'continueInPreview': 'Open Preview Mode',
      'previewModeActive': 'Preview Mode',
      'previewModeActiveSubtitle':
          'Local sample profile, cards, and nearby places are active right now.',
      'verificationEmailSent':
          'Verification email sent. Please check your inbox.',
      'profileSaved': 'Profile updated successfully.',
      'exitPreview': 'Exit Preview',
      'saveChanges': 'Save Changes',
      'add': 'Add',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'clearAll': 'Clear all',
      'quickActions': 'Quick Actions',
      'yourHealthStats': 'Your Health Stats',
      'healthTips': 'Health Tips',
      'recentActivity': 'Recent Activity',
      'seeAll': 'See All',
      'allergies': 'Allergies',
      'conditions': 'Conditions',
      'emergencyTitle': 'Emergency? Call 112',
      'emergencySubtitle':
          'Always call emergency services for life-threatening situations.',
      'noRecentActivity': 'No recent activity yet.',
      'noRecentActivitySubtitle':
          'Start checking symptoms or exploring medicines to build your history.',
      'completeProfileTitle': 'Complete your health profile',
      'completeProfileSubtitle':
          'Add the essentials once so the app can personalize symptom and medicine guidance.',
      'chooseAvatar': 'Choose an avatar',
      'bloodType': 'Blood Type',
      'weightKg': 'Weight (kg)',
      'heightCm': 'Height (cm)',
      'continueToApp': 'Continue to dashboard',
      'profileSetupHint':
          'You can edit these details later from your profile screen.',
      'personalInformation': 'Personal Information',
      'editing': 'Editing',
      'name': 'Name',
      'weight': 'Weight',
      'height': 'Height',
      'notSet': 'Not set',
      'myAllergies': 'My Allergies',
      'myConditions': 'My Conditions',
      'addAllergy': 'Add Allergy',
      'addCondition': 'Add Condition',
      'noAllergies':
          'No allergies on record yet. Add one to improve medicine safety checks.',
      'noConditions':
          'No chronic conditions on record yet. Add one to personalize recommendations.',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'english': 'English',
      'russian': 'Russian',
      'kazakh': 'Kazakh',
      'turkish': 'Turkish',
      'emailNotVerified': 'Email not verified yet',
      'resendVerification': 'Resend verification email',
      'signOut': 'Sign Out',
      'symptomChecker': 'Symptom Checker',
      'aiSymptomAnalysis': 'AI Symptom Analysis',
      'symptomAnalysisSubtitle':
          'Add your symptoms below and let the app estimate possible conditions.',
      'addSymptoms': 'Add Symptoms',
      'typeSymptom': 'Type a symptom...',
      'commonSymptoms': 'Common Symptoms',
      'selected': 'Selected ({count})',
      'analyzeSymptoms': 'Analyze Symptoms',
      'analyzing': 'Analyzing...',
      'addAtLeastOneSymptom': 'Please add at least one symptom.',
      'medicalDisclaimer':
          'This tool is for informational purposes only and does not replace professional medical advice.',
      'analyzingSymptomsTitle': 'Analyzing your symptoms...',
      'aiProcessingCount': 'Our AI is processing {count} symptom(s).',
      'matchingPatterns': 'Matching symptom patterns...',
      'evaluatingSeverity': 'Evaluating severity...',
      'generatingRecommendations': 'Generating recommendations...',
      'severity': 'Severity',
      'possibleConditions': 'Possible Conditions',
      'matchPercent': '{count}% match',
      'recommendedActions': 'Recommended Actions',
      'consultDoctor':
          'Please consult a doctor as soon as possible based on your symptoms.',
      'medicineGuide': 'Medicine Guide',
      'searchMedicines': 'Search medicines...',
      'medicineHeroTitle': 'Tap any medicine to open the full guide',
      'medicineHeroSubtitle':
          'Review dosage, warnings, side effects, storage, and save important medicines for later.',
      'noMedicinesFound': 'No medicines found',
      'noMedicinesFoundSubtitle':
          'Try a different search term or choose another category.',
      'savedMedicines': 'Saved medicines',
      'medicineViewed': 'Medicine Viewed',
      'tapToOpenFullGuide': 'Tap to open the full guide',
      'prescriptionRequired': 'Prescription Required',
      'nonPrescription': 'Over the counter',
      'allergyWarning': 'Allergy Warning',
      'allergyWarningSubtitle':
          'This medicine may contain allergens that match your profile:',
      'consultBeforeMedication':
          'Please consult your doctor before taking this medication.',
      'description': 'Description',
      'usageIndication': 'Usage and indications',
      'howToUse': 'How to Use',
      'dosage': 'Dosage',
      'warnings': 'Warnings',
      'sideEffects': 'Side Effects',
      'ingredients': 'Ingredients',
      'knownAllergens': 'Known Allergens',
      'contraindications': 'Contraindications',
      'interactions': 'Interactions',
      'storageInstructions': 'Storage instructions',
      'pregnancyBreastfeeding': 'Pregnancy and breastfeeding',
      'whenToSeeDoctor': 'When to see a doctor',
      'emergencyWarning': 'Emergency warning',
      'manufacturedBy': 'Manufactured by',
      'saveMedicine': 'Save medicine',
      'removeSavedMedicineCta': 'Remove saved medicine',
      'shareMedicine': 'Share',
      'medicineSavedForLater': 'Medicine saved for quick access.',
      'medicineRemovedFromSaved': 'Medicine removed from saved list.',
      'medicineCopiedForSharing':
          'Medicine summary copied to clipboard. Share it anywhere.',
      'medicalEducationDisclaimer':
          'This information is for educational purposes only and does not replace professional medical advice.',
      'nearbyMedicalHelp': 'Nearby Medical Help',
      'findingNearby': 'Finding locations near you...',
      'medicalMapTitle': 'Medical map',
      'medicalPlacesNearYou': 'Medical places near you',
      'loadingNearbyPlacesSubtitle':
          'Loading hospitals, clinics, pharmacies, and emergency care...',
      'nearbyPlacesReady': '{count} places ready to explore',
      'all': 'All',
      'hospital': 'Hospital',
      'clinic': 'Clinic',
      'pharmacy': 'Pharmacy',
      'emergency': 'Emergency',
      'selectedLabel': 'Selected',
      'openNow': 'Open now',
      'openShort': 'Open',
      'closed': 'Closed',
      'waitTime': 'Wait time',
      'placesFound': '{count} places found',
      'resultsCount': '{count} results',
      'gpsActive': 'GPS Active',
      'call': 'Call',
      'directions': 'Directions',
      'listView': 'List view',
      'mapView': 'Map view',
      'routeOff': 'Route off',
      'routeActive': 'Route active',
      'nearest': 'Nearest',
      'topRated': 'Top rated',
      'ratingLabel': 'Rating',
      'sortPlaces': 'Sort places',
      'sortByNearest': 'Sort by nearest',
      'sortByRating': 'Sort by rating',
      'sortByOpenNow': 'Sort by open now',
      'sortNearestLabel': 'Nearest first',
      'waitPrefix': 'Wait: {time}',
      'unableToOpenLink': 'Unable to open this action on your device.',
      'routeDirectionsUnavailable':
          'Route directions are currently unavailable.',
      'routeUnavailableLabel': 'Unavailable',
      'hospitalRouteStarted': 'Hospital route started',
      'nearbyNoPlacesAround':
          'No nearby medical places were found around your location.',
      'nearbySearchEmpty': 'No hospitals matched your search.',
      'nearbySearchFailed': 'Search failed. Please try another query.',
      'nearbyApiFailure':
          'Could not load live places. Please check your network or API setup.',
      'nearbyFallbackShown':
          'Live places are unavailable, so demo and saved medical places are shown instead.',
      'transportModes': 'Transport modes',
      'hospitalDetails': 'Hospital details',
      'addressLabel': 'Address',
      'phoneLabel': 'Phone',
      'websiteLabel': 'Website',
      'removeActivity': 'Remove activity',
      'activityRemoved': 'Activity removed.',
      'searchNearbyHint': 'Search nearby hospitals, clinics, pharmacies...',
      'savedPlaces': 'Saved Places',
      'noSavedPlaces': 'No saved places yet.',
      'noSavedPlacesSubtitle':
          'Save useful hospitals, clinics, or pharmacies to access them later.',
      'recentSearches': 'Recent Searches',
      'noRecentSearches': 'No recent searches yet.',
      'routeOptions': 'Route Options',
      'walking': 'Walking',
      'driving': 'Driving',
      'publicTransport': 'Public transport',
      'scooter': 'Scooter',
      'openWebsite': 'Open Website',
      'savePlace': 'Save Place',
      'removeSavedPlace': 'Remove Saved Place',
      'placeSaved': 'Place saved.',
      'placeRemoved': 'Place removed.',
      'distance': 'Distance',
      'coordinates': 'Coordinates',
      'startNavigation': 'Start Navigation',
      'routeUnavailable': 'Route unavailable in-app for this mode.',
      'openInMaps': 'Open in Maps',
      'currentLocation': 'Current location',
      'locationServicesDisabled':
          'Turn on location services to find nearby care.',
      'locationPermissionDenied':
          'Location permission is needed to show nearby hospitals and routes.',
      'locationPermissionDeniedForever':
          'Location permission is permanently denied. Open settings to continue.',
      'openSettings': 'Open Settings',
      'enableLocation': 'Enable Location',
      'retry': 'Retry',
      'findingYourLocation': 'Finding your location...',
      'searchResults': 'Search Results',
      'noPlacesFound': 'No places found',
      'noPlacesFoundSubtitle':
          'Try a different search or switch the medical category.',
      'loadingRoute': 'Calculating route...',
      'clearRecentSearches': 'Clear Recent Searches',
      'searchNearbyHospitals': 'Search Nearby Hospitals',
      'clearHealthData': 'Clear Health Data',
      'clearHealthDataSubtitle':
          'Remove allergies, conditions, measurements, and recent activity from your profile?',
      'healthDataCleared': 'Health data cleared.',
      'confirm': 'Confirm',
      'checkups': 'Checkups',
      'now': 'Now',
      'minutesAgo': '{count}m ago',
      'hoursAgo': '{count}h ago',
      'daysAgo': '{count}d ago',
      'onboardingFeatureAnalysis': 'AI-powered analysis',
      'onboardingFeatureSeverity': 'Severity assessment',
      'onboardingFeatureGuidance': 'Treatment guidance',
      'onboardingFeatureSafety': 'Medicine safety checks',
      'onboardingFeatureWarnings': 'Allergy-aware warnings',
      'onboardingFeatureDosing': 'Dosing information',
      'onboardingFeatureClinics': 'Clinics and hospitals',
      'onboardingFeaturePharmacies': 'Pharmacies nearby',
      'onboardingFeatureContacts': 'Emergency contacts',
      'onboardingTitle1': 'Your AI health companion',
      'onboardingSubtitle1':
          'MediGuide AI helps you understand symptoms, medicines, and care options in one place.',
      'onboardingTitle2': 'Smart symptom analysis',
      'onboardingSubtitle2':
          'Check symptoms, review severity, and see what action to take next.',
      'onboardingTitle3': 'Medicine safety and allergies',
      'onboardingSubtitle3':
          'Compare medicines against your allergy profile before you take them.',
      'onboardingTitle4': 'Find nearby medical help',
      'onboardingSubtitle4':
          'Browse clinics, hospitals, pharmacies, and emergency points nearby.',
      'greetingMorning': 'Good morning',
      'greetingAfternoon': 'Good afternoon',
      'greetingEvening': 'Good evening',
      'greetingNight': 'Good night',
    },
    'ru': {
      'appName': 'MediGuide AI',
      'appTagline': 'Ваш умный помощник по здоровью',
      'loadingProfile': 'Загружаем ваш медицинский профиль...',
      'loading': 'Загрузка...',
      'skip': 'Пропустить',
      'next': 'Далее',
      'getStarted': 'Начать',
      'home': 'Главная',
      'symptoms': 'Симптомы',
      'medicines': 'Лекарства',
      'nearby': 'Рядом',
      'profile': 'Профиль',
      'signIn': 'Войти',
      'signUp': 'Регистрация',
      'signInWithGoogle': 'Продолжить через Google',
      'fullName': 'Полное имя',
      'email': 'Email',
      'password': 'Пароль',
      'welcomeBack': 'С возвращением',
      'createAccount': 'Создать аккаунт',
      'signInSubtitle': 'Войдите, чтобы продолжить работу с приложением.',
      'signUpSubtitle':
          'Создайте аккаунт и начните безопасно отслеживать здоровье.',
      'orContinueWith': 'или продолжить через',
      'invalidEmailAddress': 'Введите корректный email.',
      'minimumPasswordLength': 'Минимум 6 символов.',
      'authFailed': 'Не удалось выполнить вход.',
      'googleSignInFailed': 'Не удалось войти через Google.',
      'checkingFirebaseSetup': 'Проверяем настройку Firebase',
      'checkingFirebaseSetupSubtitle':
          'Проверяем Authentication и конфигурацию проекта перед входом.',
      'firebaseSetupRequired': 'Firebase Authentication не настроен',
      'firebaseSetupRequiredSubtitle':
          'Этот проект сейчас возвращает CONFIGURATION_NOT_FOUND. Включите Firebase Authentication, активируйте Email/Password и Google, добавьте Android SHA-ключи и скачайте новый google-services.json.',
      'firebaseSetupNetworkIssue': 'Не удалось проверить Firebase',
      'firebaseSetupNetworkIssueSubtitle':
          'Сейчас не удалось проверить Firebase Authentication. Проверьте интернет и повторите попытку.',
      'retryConfigurationCheck': 'Проверить снова',
      'previewModeTitle': 'Открыть интерфейс в режиме предпросмотра',
      'previewModeSubtitle':
          'Используйте локальные демо-данные, чтобы открыть дашборд, карточки и карту ближайшей медпомощи, пока Firebase или Google API недоступны.',
      'continueInPreview': 'Открыть предпросмотр',
      'previewModeActive': 'Режим предпросмотра',
      'previewModeActiveSubtitle':
          'Сейчас используются локальный демо-профиль, карточки и ближайшие места.',
      'verificationEmailSent':
          'Письмо с подтверждением отправлено. Проверьте почту.',
      'profileSaved': 'Профиль успешно обновлён.',
      'exitPreview': 'Выйти из предпросмотра',
      'saveChanges': 'Сохранить',
      'add': 'Добавить',
      'delete': 'Удалить',
      'cancel': 'Отмена',
      'clearAll': 'Очистить всё',
      'quickActions': 'Быстрые действия',
      'yourHealthStats': 'Ваши показатели',
      'healthTips': 'Советы по здоровью',
      'recentActivity': 'Недавняя активность',
      'seeAll': 'Все',
      'allergies': 'Аллергии',
      'conditions': 'Состояния',
      'emergencyTitle': 'Экстренно? Позвоните 112',
      'emergencySubtitle':
          'При угрозе жизни всегда звоните в экстренные службы.',
      'noRecentActivity': 'Пока нет активности.',
      'noRecentActivitySubtitle':
          'Начните проверять симптомы или изучать лекарства, чтобы заполнить историю.',
      'completeProfileTitle': 'Заполните медицинский профиль',
      'completeProfileSubtitle':
          'Укажите базовые данные один раз, чтобы получать персональные рекомендации.',
      'chooseAvatar': 'Выберите аватар',
      'bloodType': 'Группа крови',
      'weightKg': 'Вес (кг)',
      'heightCm': 'Рост (см)',
      'continueToApp': 'Перейти в приложение',
      'profileSetupHint': 'Позже вы сможете изменить эти данные в профиле.',
      'personalInformation': 'Личная информация',
      'editing': 'Редактирование',
      'name': 'Имя',
      'weight': 'Вес',
      'height': 'Рост',
      'notSet': 'Не указано',
      'myAllergies': 'Мои аллергии',
      'myConditions': 'Мои состояния',
      'addAllergy': 'Добавить аллергию',
      'addCondition': 'Добавить состояние',
      'noAllergies':
          'Аллергии пока не добавлены. Добавьте их для проверки безопасности лекарств.',
      'noConditions':
          'Состояния пока не добавлены. Добавьте их для персональных рекомендаций.',
      'settings': 'Настройки',
      'theme': 'Тема',
      'language': 'Язык',
      'light': 'Светлая',
      'dark': 'Тёмная',
      'system': 'Системная',
      'english': 'Английский',
      'russian': 'Русский',
      'kazakh': 'Казахский',
      'turkish': 'Турецкий',
      'emailNotVerified': 'Email ещё не подтверждён',
      'resendVerification': 'Отправить письмо повторно',
      'signOut': 'Выйти',
      'symptomChecker': 'Проверка симптомов',
      'aiSymptomAnalysis': 'AI-анализ симптомов',
      'symptomAnalysisSubtitle':
          'Добавьте симптомы ниже, и приложение оценит возможные состояния.',
      'addSymptoms': 'Добавить симптомы',
      'typeSymptom': 'Введите симптом...',
      'commonSymptoms': 'Частые симптомы',
      'selected': 'Выбрано ({count})',
      'analyzeSymptoms': 'Анализировать симптомы',
      'analyzing': 'Анализируем...',
      'addAtLeastOneSymptom': 'Добавьте хотя бы один симптом.',
      'medicalDisclaimer':
          'Инструмент носит информационный характер и не заменяет консультацию врача.',
      'analyzingSymptomsTitle': 'Анализируем ваши симптомы...',
      'aiProcessingCount': 'AI обрабатывает {count} симптом(ов).',
      'matchingPatterns': 'Сопоставляем паттерны симптомов...',
      'evaluatingSeverity': 'Оцениваем тяжесть...',
      'generatingRecommendations': 'Формируем рекомендации...',
      'severity': 'Тяжесть',
      'possibleConditions': 'Возможные состояния',
      'matchPercent': 'Совпадение {count}%',
      'recommendedActions': 'Рекомендуемые действия',
      'consultDoctor':
          'Пожалуйста, как можно скорее обратитесь к врачу по вашим симптомам.',
      'medicineGuide': 'Справочник лекарств',
      'searchMedicines': 'Найти лекарство...',
      'medicineHeroTitle': 'Нажмите на лекарство, чтобы открыть полный гид',
      'medicineHeroSubtitle':
          'Смотрите дозировку, предупреждения, побочные эффекты, хранение и сохраняйте важные лекарства.',
      'noMedicinesFound': 'Лекарства не найдены',
      'noMedicinesFoundSubtitle': 'Попробуйте другой запрос или категорию.',
      'savedMedicines': 'Сохранённые лекарства',
      'medicineViewed': 'Просмотрено лекарство',
      'tapToOpenFullGuide': 'Нажмите, чтобы открыть полное описание',
      'prescriptionRequired': 'Нужен рецепт',
      'nonPrescription': 'Без рецепта',
      'allergyWarning': 'Предупреждение об аллергии',
      'allergyWarningSubtitle':
          'Это лекарство может содержать аллергены из вашего профиля:',
      'consultBeforeMedication':
          'Пожалуйста, проконсультируйтесь с врачом перед приёмом.',
      'description': 'Описание',
      'usageIndication': 'Показания и применение',
      'howToUse': 'Как принимать',
      'dosage': 'Дозировка',
      'warnings': 'Предупреждения',
      'sideEffects': 'Побочные эффекты',
      'ingredients': 'Состав',
      'knownAllergens': 'Известные аллергены',
      'contraindications': 'Противопоказания',
      'interactions': 'Взаимодействия',
      'storageInstructions': 'Условия хранения',
      'pregnancyBreastfeeding': 'Беременность и грудное вскармливание',
      'whenToSeeDoctor': 'Когда обратиться к врачу',
      'emergencyWarning': 'Экстренное предупреждение',
      'manufacturedBy': 'Производитель',
      'saveMedicine': 'Сохранить лекарство',
      'removeSavedMedicineCta': 'Убрать из сохранённых',
      'shareMedicine': 'Поделиться',
      'medicineSavedForLater': 'Лекарство сохранено для быстрого доступа.',
      'medicineRemovedFromSaved': 'Лекарство удалено из сохранённых.',
      'medicineCopiedForSharing':
          'Краткая информация о лекарстве скопирована в буфер обмена.',
      'medicalEducationDisclaimer':
          'Эта информация предназначена только для образовательных целей и не заменяет профессиональную медицинскую консультацию.',
      'nearbyMedicalHelp': 'Медицинская помощь рядом',
      'findingNearby': 'Ищем места рядом с вами...',
      'medicalMapTitle': 'Медицинская карта',
      'medicalPlacesNearYou': 'Медицинские места рядом с вами',
      'loadingNearbyPlacesSubtitle':
          'Загружаем больницы, клиники, аптеки и экстренную помощь...',
      'nearbyPlacesReady': 'Доступно мест: {count}',
      'all': 'Все',
      'hospital': 'Больница',
      'clinic': 'Клиника',
      'pharmacy': 'Аптека',
      'emergency': 'Экстренно',
      'selectedLabel': 'Выбрано',
      'openNow': 'Открыто',
      'openShort': 'Открыто',
      'closed': 'Закрыто',
      'waitTime': 'Время ожидания',
      'placesFound': 'Найдено мест: {count}',
      'resultsCount': 'Результатов: {count}',
      'gpsActive': 'GPS активен',
      'call': 'Позвонить',
      'directions': 'Маршрут',
      'listView': 'Список',
      'mapView': 'Карта',
      'routeOff': 'Маршрут выкл.',
      'routeActive': 'Маршрут активен',
      'nearest': 'Ближайшие',
      'topRated': 'Лучший рейтинг',
      'ratingLabel': 'Рейтинг',
      'sortPlaces': 'Сортировка',
      'sortByNearest': 'Сначала ближайшие',
      'sortByRating': 'Сортировать по рейтингу',
      'sortByOpenNow': 'Сортировать по открытым',
      'sortNearestLabel': 'Ближайшие сначала',
      'waitPrefix': 'Ожидание: {time}',
      'unableToOpenLink': 'Не удалось открыть действие на этом устройстве.',
      'routeDirectionsUnavailable': 'Маршрут сейчас недоступен.',
      'routeUnavailableLabel': 'Недоступно',
      'hospitalRouteStarted': 'Маршрут до больницы построен',
      'nearbyNoPlacesAround':
          'Рядом с вашим местоположением медицинские места не найдены.',
      'nearbySearchEmpty': 'По вашему запросу больницы не найдены.',
      'nearbySearchFailed': 'Поиск не удался. Попробуйте другой запрос.',
      'nearbyApiFailure':
          'Не удалось загрузить живые данные мест. Проверьте сеть или настройку API.',
      'nearbyFallbackShown':
          'Живые данные недоступны, поэтому показаны демо и сохранённые медицинские места.',
      'transportModes': 'Режимы транспорта',
      'hospitalDetails': 'Детали больницы',
      'addressLabel': 'Адрес',
      'phoneLabel': 'Телефон',
      'websiteLabel': 'Сайт',
      'removeActivity': 'Удалить активность',
      'activityRemoved': 'Активность удалена.',
      'searchNearbyHint': 'Ищите рядом больницы, клиники, аптеки...',
      'savedPlaces': 'Сохранённые места',
      'noSavedPlaces': 'Пока нет сохранённых мест.',
      'noSavedPlacesSubtitle':
          'Сохраняйте полезные больницы, клиники и аптеки для быстрого доступа.',
      'recentSearches': 'Недавние поиски',
      'noRecentSearches': 'Пока нет недавних поисков.',
      'routeOptions': 'Варианты маршрута',
      'walking': 'Пешком',
      'driving': 'На машине',
      'publicTransport': 'Общественный транспорт',
      'scooter': 'Скутер',
      'openWebsite': 'Открыть сайт',
      'savePlace': 'Сохранить место',
      'removeSavedPlace': 'Убрать из сохранённых',
      'placeSaved': 'Место сохранено.',
      'placeRemoved': 'Место удалено.',
      'distance': 'Расстояние',
      'coordinates': 'Координаты',
      'startNavigation': 'Начать маршрут',
      'routeUnavailable':
          'Маршрут для этого режима недоступен внутри приложения.',
      'openInMaps': 'Открыть в Maps',
      'currentLocation': 'Текущее местоположение',
      'locationServicesDisabled':
          'Включите геолокацию, чтобы находить помощь рядом.',
      'locationPermissionDenied':
          'Нужно разрешение на геолокацию, чтобы показать больницы рядом и маршруты.',
      'locationPermissionDeniedForever':
          'Доступ к геолокации запрещён навсегда. Откройте настройки и разрешите его.',
      'openSettings': 'Открыть настройки',
      'enableLocation': 'Включить геолокацию',
      'retry': 'Повторить',
      'findingYourLocation': 'Определяем ваше местоположение...',
      'searchResults': 'Результаты поиска',
      'noPlacesFound': 'Места не найдены',
      'noPlacesFoundSubtitle':
          'Попробуйте другой запрос или переключите медицинскую категорию.',
      'loadingRoute': 'Строим маршрут...',
      'clearRecentSearches': 'Очистить недавние поиски',
      'searchNearbyHospitals': 'Найти больницы рядом',
      'clearHealthData': 'Очистить медицинские данные',
      'clearHealthDataSubtitle':
          'Удалить аллергии, состояния, параметры и недавнюю активность из профиля?',
      'healthDataCleared': 'Медицинские данные очищены.',
      'confirm': 'Подтвердить',
      'checkups': 'Осмотры',
      'now': 'Сейчас',
      'minutesAgo': '{count} мин назад',
      'hoursAgo': '{count} ч назад',
      'daysAgo': '{count} дн назад',
      'onboardingFeatureAnalysis': 'AI-анализ симптомов',
      'onboardingFeatureSeverity': 'Оценка тяжести',
      'onboardingFeatureGuidance': 'Подсказки по лечению',
      'onboardingFeatureSafety': 'Проверка безопасности лекарств',
      'onboardingFeatureWarnings': 'Предупреждения с учётом аллергий',
      'onboardingFeatureDosing': 'Информация по дозировке',
      'onboardingFeatureClinics': 'Клиники и больницы',
      'onboardingFeaturePharmacies': 'Аптеки рядом',
      'onboardingFeatureContacts': 'Экстренные контакты',
      'onboardingTitle1': 'Ваш AI-помощник по здоровью',
      'onboardingSubtitle1':
          'MediGuide AI помогает понять симптомы, лекарства и варианты помощи в одном месте.',
      'onboardingTitle2': 'Умный анализ симптомов',
      'onboardingSubtitle2':
          'Проверяйте симптомы, оценивайте риск и понимайте следующий шаг.',
      'onboardingTitle3': 'Безопасность лекарств и аллергии',
      'onboardingSubtitle3':
          'Сравнивайте лекарства со своим профилем аллергий до приёма.',
      'onboardingTitle4': 'Найдите помощь рядом',
      'onboardingSubtitle4':
          'Просматривайте ближайшие клиники, больницы, аптеки и экстренные пункты.',
      'greetingMorning': 'Доброе утро',
      'greetingAfternoon': 'Добрый день',
      'greetingEvening': 'Добрый вечер',
      'greetingNight': 'Доброй ночи',
    },
    'kk': {
      'appName': 'MediGuide AI',
      'appTagline': 'Сіздің ақылды денсаулық көмекшіңіз',
      'loadingProfile': 'Медициналық профиліңіз жүктеліп жатыр...',
      'loading': 'Жүктелуде...',
      'skip': 'Өткізу',
      'next': 'Келесі',
      'getStarted': 'Бастау',
      'home': 'Басты бет',
      'symptoms': 'Симптомдар',
      'medicines': 'Дәрілер',
      'nearby': 'Жақын жерде',
      'profile': 'Профиль',
      'signIn': 'Кіру',
      'signUp': 'Тіркелу',
      'signInWithGoogle': 'Google арқылы жалғастыру',
      'fullName': 'Толық аты-жөні',
      'email': 'Email',
      'password': 'Құпиясөз',
      'welcomeBack': 'Қайта қош келдіңіз',
      'createAccount': 'Аккаунт ашу',
      'signInSubtitle': 'Денсаулық жолыңызды жалғастыру үшін кіріңіз.',
      'signUpSubtitle':
          'Аккаунт ашып, денсаулығыңызды қауіпсіз бақылауды бастаңыз.',
      'orContinueWith': 'немесе мына арқылы жалғастырыңыз',
      'invalidEmailAddress': 'Дұрыс email енгізіңіз.',
      'minimumPasswordLength': 'Кемінде 6 таңба.',
      'authFailed': 'Кіру орындалмады.',
      'googleSignInFailed': 'Google арқылы кіру орындалмады.',
      'checkingFirebaseSetup': 'Firebase баптауы тексеріліп жатыр',
      'checkingFirebaseSetupSubtitle':
          'Кіру алдында Authentication және жоба конфигурациясы тексерілуде.',
      'firebaseSetupRequired': 'Firebase Authentication әлі бапталмаған',
      'firebaseSetupRequiredSubtitle':
          'Бұл жоба қазір CONFIGURATION_NOT_FOUND қайтарады. Firebase Authentication-ды қосыңыз, Email/Password пен Google provider-лерін іске қосыңыз, Android SHA кілттерін қосып, жаңа google-services.json жүктеңіз.',
      'firebaseSetupNetworkIssue': 'Firebase тексеру мүмкін болмады',
      'firebaseSetupNetworkIssueSubtitle':
          'Қазір Firebase Authentication-ды тексеру мүмкін болмады. Интернетті тексеріп, қайта көріңіз.',
      'retryConfigurationCheck': 'Қайта тексеру',
      'previewModeTitle': 'Интерфейсті preview режимінде ашу',
      'previewModeSubtitle':
          'Firebase немесе Google API істемей тұрса да, дашбордты, карточкаларды және жақын медициналық карта бөлімін жергілікті demo деректермен ашыңыз.',
      'continueInPreview': 'Preview режимін ашу',
      'previewModeActive': 'Preview режимі',
      'previewModeActiveSubtitle':
          'Қазір жергілікті demo профиль, карточкалар және жақын орындар көрсетіліп тұр.',
      'verificationEmailSent': 'Растау хаты жіберілді. Поштаңызды тексеріңіз.',
      'profileSaved': 'Профиль сәтті жаңартылды.',
      'exitPreview': 'Preview-ден шығу',
      'saveChanges': 'Сақтау',
      'add': 'Қосу',
      'delete': 'Жою',
      'cancel': 'Бас тарту',
      'clearAll': 'Барлығын тазалау',
      'quickActions': 'Жылдам әрекеттер',
      'yourHealthStats': 'Сіздің көрсеткіштеріңіз',
      'healthTips': 'Денсаулық кеңестері',
      'recentActivity': 'Соңғы белсенділік',
      'seeAll': 'Барлығы',
      'allergies': 'Аллергиялар',
      'conditions': 'Жағдайлар',
      'emergencyTitle': 'Шұғыл жағдай ма? 112 нөміріне қоңырау шалыңыз',
      'emergencySubtitle':
          'Өмірге қауіп төнген жағдайда әрқашан жедел қызметке хабарласыңыз.',
      'noRecentActivity': 'Әзірге белсенділік жоқ.',
      'noRecentActivitySubtitle':
          'Тарихты толтыру үшін симптомдарды тексеріп немесе дәрілерді қараңыз.',
      'completeProfileTitle': 'Денсаулық профилін толтырыңыз',
      'completeProfileSubtitle':
          'Жеке ұсыныстар алу үшін негізгі мәліметтерді бір рет енгізіңіз.',
      'chooseAvatar': 'Аватар таңдаңыз',
      'bloodType': 'Қан тобы',
      'weightKg': 'Салмақ (кг)',
      'heightCm': 'Бойы (см)',
      'continueToApp': 'Қосымшаға өту',
      'profileSetupHint':
          'Бұл мәліметтерді кейін профиль бетінде өзгерте аласыз.',
      'personalInformation': 'Жеке ақпарат',
      'editing': 'Өңдеу',
      'name': 'Аты',
      'weight': 'Салмақ',
      'height': 'Бойы',
      'notSet': 'Көрсетілмеген',
      'myAllergies': 'Менің аллергияларым',
      'myConditions': 'Менің жағдайларым',
      'addAllergy': 'Аллергия қосу',
      'addCondition': 'Жағдай қосу',
      'noAllergies':
          'Әзірге аллергия тіркелмеген. Дәрі қауіпсіздігін тексеру үшін қосыңыз.',
      'noConditions':
          'Әзірге жағдай тіркелмеген. Ұсыныстарды жекелеу үшін қосыңыз.',
      'settings': 'Баптаулар',
      'theme': 'Тақырып',
      'language': 'Тіл',
      'light': 'Ашық',
      'dark': 'Қараңғы',
      'system': 'Жүйелік',
      'english': 'Ағылшын',
      'russian': 'Орыс',
      'kazakh': 'Қазақ',
      'turkish': 'Түрік',
      'emailNotVerified': 'Email әлі расталмаған',
      'resendVerification': 'Растау хатын қайта жіберу',
      'signOut': 'Шығу',
      'symptomChecker': 'Симптом тексеру',
      'aiSymptomAnalysis': 'AI симптом талдауы',
      'symptomAnalysisSubtitle':
          'Төменге симптомдарды қосыңыз, қосымша ықтимал жағдайларды бағалайды.',
      'addSymptoms': 'Симптом қосу',
      'typeSymptom': 'Симптом жазыңыз...',
      'commonSymptoms': 'Жиі симптомдар',
      'selected': 'Таңдалды ({count})',
      'analyzeSymptoms': 'Симптомдарды талдау',
      'analyzing': 'Талданып жатыр...',
      'addAtLeastOneSymptom': 'Кемінде бір симптом қосыңыз.',
      'medicalDisclaimer':
          'Бұл құрал тек ақпараттық мақсатқа арналған және дәрігер кеңесін алмастырмайды.',
      'analyzingSymptomsTitle': 'Симптомдарыңыз талданып жатыр...',
      'aiProcessingCount': 'AI {count} симптомды өңдеп жатыр.',
      'matchingPatterns': 'Симптом үлгілерін салыстырып жатыр...',
      'evaluatingSeverity': 'Ауырлығын бағалап жатыр...',
      'generatingRecommendations': 'Ұсыныстар дайындап жатыр...',
      'severity': 'Ауырлығы',
      'possibleConditions': 'Ықтимал жағдайлар',
      'matchPercent': '{count}% сәйкестік',
      'recommendedActions': 'Ұсынылатын әрекеттер',
      'consultDoctor':
          'Симптомдарыңызға байланысты мүмкіндігінше тезірек дәрігерге көрініңіз.',
      'medicineGuide': 'Дәрі анықтамалығы',
      'searchMedicines': 'Дәрі іздеу...',
      'medicineHeroTitle': 'Кез келген дәріні басып, толық гидті ашыңыз',
      'medicineHeroSubtitle':
          'Дозаны, ескертулерді, жанама әсерлерді, сақтау тәсілін қарап, маңызды дәрілерді сақтап қойыңыз.',
      'noMedicinesFound': 'Дәрі табылмады',
      'noMedicinesFoundSubtitle': 'Басқа сұрау не санатты қолданып көріңіз.',
      'savedMedicines': 'Сақталған дәрілер',
      'medicineViewed': 'Дәрі қаралды',
      'tapToOpenFullGuide': 'Толық ақпаратты ашу үшін басыңыз',
      'prescriptionRequired': 'Рецепт керек',
      'nonPrescription': 'Рецептсіз',
      'allergyWarning': 'Аллергия туралы ескерту',
      'allergyWarningSubtitle':
          'Бұл дәрі сіздің профиліңіздегі аллергендермен сәйкес келуі мүмкін:',
      'consultBeforeMedication': 'Қолданар алдында дәрігермен кеңесіңіз.',
      'description': 'Сипаттама',
      'usageIndication': 'Қолданылуы мен көрсетілімдері',
      'howToUse': 'Қолдану жолы',
      'dosage': 'Дозасы',
      'warnings': 'Ескертулер',
      'sideEffects': 'Жанама әсерлер',
      'ingredients': 'Құрамы',
      'knownAllergens': 'Белгілі аллергендер',
      'contraindications': 'Қарсы көрсетілімдер',
      'interactions': 'Өзара әрекеттесулер',
      'storageInstructions': 'Сақтау нұсқаулығы',
      'pregnancyBreastfeeding': 'Жүктілік және емізу',
      'whenToSeeDoctor': 'Қашан дәрігерге көріну керек',
      'emergencyWarning': 'Шұғыл ескерту',
      'manufacturedBy': 'Өндіруші',
      'saveMedicine': 'Дәріні сақтау',
      'removeSavedMedicineCta': 'Сақталғаннан алып тастау',
      'shareMedicine': 'Бөлісу',
      'medicineSavedForLater': 'Дәрі жылдам қолжетімділік үшін сақталды.',
      'medicineRemovedFromSaved': 'Дәрі сақталған тізімнен алынды.',
      'medicineCopiedForSharing':
          'Дәрі туралы қысқаша мәлімет алмасу буферіне көшірілді.',
      'medicalEducationDisclaimer':
          'Бұл ақпарат тек білім беру мақсатында берілген және кәсіби медициналық кеңесті алмастырмайды.',
      'nearbyMedicalHelp': 'Жақын маңдағы медициналық көмек',
      'findingNearby': 'Сізге жақын орындар ізделуде...',
      'medicalMapTitle': 'Медициналық карта',
      'medicalPlacesNearYou': 'Жақын медициналық орындар',
      'loadingNearbyPlacesSubtitle':
          'Ауруханалар, клиникалар, дәріханалар және шұғыл көмек жүктеліп жатыр...',
      'all': 'Барлығы',
      'hospital': 'Аурухана',
      'clinic': 'Клиника',
      'pharmacy': 'Дәріхана',
      'emergency': 'Жедел',
      'selectedLabel': 'Таңдалды',
      'openNow': 'Ашық',
      'openShort': 'Ашық',
      'closed': 'Жабық',
      'waitTime': 'Күту уақыты',
      'placesFound': '{count} орын табылды',
      'nearbyPlacesReady': 'Қарауға дайын орындар: {count}',
      'resultsCount': 'Нәтиже: {count}',
      'gpsActive': 'GPS белсенді',
      'call': 'Қоңырау шалу',
      'directions': 'Бағыт',
      'listView': 'Тізім',
      'mapView': 'Карта',
      'routeOff': 'Маршрут өшірулі',
      'routeActive': 'Маршрут белсенді',
      'nearest': 'Жақын',
      'topRated': 'Үздік рейтинг',
      'ratingLabel': 'Рейтинг',
      'sortPlaces': 'Сұрыптау',
      'sortByNearest': 'Жақындығы бойынша',
      'sortByRating': 'Рейтинг бойынша',
      'sortByOpenNow': 'Қазір ашықтары бойынша',
      'sortNearestLabel': 'Алдымен ең жақын',
      'waitPrefix': 'Күту: {time}',
      'unableToOpenLink': 'Бұл әрекетті құрылғыда ашу мүмкін болмады.',
      'routeDirectionsUnavailable': 'Маршрут қазір қолжетімсіз.',
      'routeUnavailableLabel': 'Қолжетімсіз',
      'hospitalRouteStarted': 'Ауруханаға маршрут басталды',
      'nearbyNoPlacesAround':
          'Орналасқан жеріңіздің маңында медициналық орындар табылмады.',
      'nearbySearchEmpty': 'Іздеуіңізге сай ауруханалар табылмады.',
      'nearbySearchFailed':
          'Іздеу сәтсіз аяқталды. Басқа сұрау қолданып көріңіз.',
      'nearbyApiFailure':
          'Тікелей орындарды жүктеу мүмкін болмады. Желіні немесе API баптауын тексеріңіз.',
      'nearbyFallbackShown':
          'Тікелей дерек қолжетімсіз болғандықтан, demo және сақталған медициналық орындар көрсетілді.',
      'transportModes': 'Көлік режимдері',
      'hospitalDetails': 'Аурухана туралы мәлімет',
      'addressLabel': 'Мекенжай',
      'phoneLabel': 'Телефон',
      'websiteLabel': 'Сайт',
      'removeActivity': 'Белсенділікті өшіру',
      'activityRemoved': 'Белсенділік өшірілді.',
      'searchNearbyHint': 'Жақын аурухана, клиника, дәріхана іздеңіз...',
      'savedPlaces': 'Сақталған орындар',
      'noSavedPlaces': 'Әзірге сақталған орындар жоқ.',
      'noSavedPlacesSubtitle':
          'Кейін тез ашу үшін пайдалы аурухана, клиника және дәріханаларды сақтаңыз.',
      'recentSearches': 'Соңғы іздеулер',
      'noRecentSearches': 'Әзірге соңғы іздеулер жоқ.',
      'routeOptions': 'Маршрут нұсқалары',
      'walking': 'Жаяу',
      'driving': 'Көлікпен',
      'publicTransport': 'Қоғамдық көлік',
      'scooter': 'Скутер',
      'openWebsite': 'Сайтты ашу',
      'savePlace': 'Орынды сақтау',
      'removeSavedPlace': 'Сақтаудан өшіру',
      'placeSaved': 'Орын сақталды.',
      'placeRemoved': 'Орын өшірілді.',
      'distance': 'Қашықтық',
      'coordinates': 'Координаттар',
      'startNavigation': 'Маршрутты бастау',
      'routeUnavailable': 'Бұл режим үшін қолданба ішінде маршрут қолжетімсіз.',
      'openInMaps': 'Maps-та ашу',
      'currentLocation': 'Қазіргі орналасу',
      'locationServicesDisabled':
          'Жақын көмекті табу үшін геолокацияны қосыңыз.',
      'locationPermissionDenied':
          'Жақын ауруханалар мен маршруттарды көру үшін геолокация рұқсаты керек.',
      'locationPermissionDeniedForever':
          'Геолокацияға рұқсат біржола өшірілген. Жалғастыру үшін баптауларды ашыңыз.',
      'openSettings': 'Баптауларды ашу',
      'enableLocation': 'Геолокацияны қосу',
      'retry': 'Қайталау',
      'findingYourLocation': 'Орналасуыңыз анықталып жатыр...',
      'searchResults': 'Іздеу нәтижелері',
      'noPlacesFound': 'Орындар табылмады',
      'noPlacesFoundSubtitle':
          'Басқа сұрауды байқап көріңіз немесе медициналық санатты ауыстырыңыз.',
      'loadingRoute': 'Маршрут есептеліп жатыр...',
      'clearRecentSearches': 'Соңғы іздеулерді тазалау',
      'searchNearbyHospitals': 'Жақын ауруханаларды іздеу',
      'clearHealthData': 'Денсаулық деректерін тазалау',
      'clearHealthDataSubtitle':
          'Аллергияларды, жағдайларды, өлшемдерді және соңғы белсенділікті профиліңізден өшіру керек пе?',
      'healthDataCleared': 'Денсаулық деректері тазаланды.',
      'confirm': 'Растау',
      'checkups': 'Тексерулер',
      'now': 'Қазір',
      'minutesAgo': '{count} мин бұрын',
      'hoursAgo': '{count} сағ бұрын',
      'daysAgo': '{count} күн бұрын',
      'onboardingFeatureAnalysis': 'AI талдауы',
      'onboardingFeatureSeverity': 'Ауырлығын бағалау',
      'onboardingFeatureGuidance': 'Емдеу бойынша бағыт',
      'onboardingFeatureSafety': 'Дәрі қауіпсіздігін тексеру',
      'onboardingFeatureWarnings': 'Аллергияға бейімделген ескертулер',
      'onboardingFeatureDosing': 'Дозалау ақпараты',
      'onboardingFeatureClinics': 'Клиникалар мен ауруханалар',
      'onboardingFeaturePharmacies': 'Жақын дәріханалар',
      'onboardingFeatureContacts': 'Шұғыл байланыстар',
      'onboardingTitle1': 'AI денсаулық көмекшіңіз',
      'onboardingSubtitle1':
          'MediGuide AI симптомдар, дәрілер және көмек нұсқаларын бір жерде жинайды.',
      'onboardingTitle2': 'Ақылды симптом талдауы',
      'onboardingSubtitle2':
          'Симптомдарды тексеріп, қауіпті бағалап, келесі қадамды біліңіз.',
      'onboardingTitle3': 'Дәрі қауіпсіздігі және аллергия',
      'onboardingSubtitle3':
          'Дәрілерді қабылдамас бұрын оларды аллергия профиліңізбен салыстырыңыз.',
      'onboardingTitle4': 'Жақын көмекті табыңыз',
      'onboardingSubtitle4':
          'Жақын жердегі клиника, аурухана, дәріхана және жедел орындарды қараңыз.',
      'greetingMorning': 'Қайырлы таң',
      'greetingAfternoon': 'Қайырлы күн',
      'greetingEvening': 'Қайырлы кеш',
      'greetingNight': 'Қайырлы түн',
    },
    'tr': {
      'appName': 'MediGuide AI',
      'appTagline': 'Akıllı sağlık yardımcınız',
      'loadingProfile': 'Sağlık profiliniz yükleniyor...',
      'loading': 'Yükleniyor...',
      'skip': 'Geç',
      'next': 'İleri',
      'getStarted': 'Başla',
      'home': 'Ana Sayfa',
      'symptoms': 'Belirtiler',
      'medicines': 'İlaçlar',
      'nearby': 'Yakında',
      'profile': 'Profil',
      'signIn': 'Giriş Yap',
      'signUp': 'Kayıt Ol',
      'signInWithGoogle': 'Google ile devam et',
      'fullName': 'Ad Soyad',
      'email': 'Email',
      'password': 'Şifre',
      'welcomeBack': 'Tekrar hoş geldiniz',
      'createAccount': 'Hesap oluştur',
      'signInSubtitle': 'Sağlık yolculuğunuza devam etmek için giriş yapın.',
      'signUpSubtitle':
          'Hesabınızı oluşturun ve sağlığınızı güvenle takip etmeye başlayın.',
      'orContinueWith': 'veya bununla devam et',
      'invalidEmailAddress': 'Lütfen geçerli bir email adresi girin.',
      'minimumPasswordLength': 'En az 6 karakter.',
      'authFailed': 'Giriş başarısız oldu.',
      'googleSignInFailed': 'Google ile giriş başarısız oldu.',
      'checkingFirebaseSetup': 'Firebase kurulumu kontrol ediliyor',
      'checkingFirebaseSetupSubtitle':
          'Girişten önce Authentication ve proje yapılandırması doğrulanıyor.',
      'firebaseSetupRequired': 'Firebase Authentication kurulumu gerekiyor',
      'firebaseSetupRequiredSubtitle':
          'Bu proje şu anda CONFIGURATION_NOT_FOUND döndürüyor. Firebase Authentication\'ı etkinleştirin, Email/Password ve Google sağlayıcılarını açın, Android SHA anahtarlarını ekleyin ve yeni google-services.json dosyasını indirin.',
      'firebaseSetupNetworkIssue': 'Firebase kurulumu doğrulanamadı',
      'firebaseSetupNetworkIssueSubtitle':
          'Firebase Authentication şu anda kontrol edilemedi. Internet baglantinizi kontrol edip tekrar deneyin.',
      'retryConfigurationCheck': 'Yeniden Dene',
      'previewModeTitle': 'Arayuzu onizleme modunda ac',
      'previewModeSubtitle':
          'Firebase veya Google API kullanilamazken paneli, kartlari ve yakin tibbi yardim haritasini yerel demo verileriyle acin.',
      'continueInPreview': 'Onizleme Modunu Ac',
      'previewModeActive': 'Onizleme Modu',
      'previewModeActiveSubtitle':
          'Su anda yerel demo profil, kartlar ve yakin yerler kullaniliyor.',
      'verificationEmailSent':
          'Doğrulama e-postası gönderildi. Gelen kutunuzu kontrol edin.',
      'profileSaved': 'Profil başarıyla güncellendi.',
      'exitPreview': 'Onizlemeden Cik',
      'saveChanges': 'Kaydet',
      'add': 'Ekle',
      'delete': 'Sil',
      'cancel': 'İptal',
      'clearAll': 'Tümünü temizle',
      'quickActions': 'Hızlı İşlemler',
      'yourHealthStats': 'Sağlık İstatistikleriniz',
      'healthTips': 'Sağlık İpuçları',
      'recentActivity': 'Son Etkinlik',
      'seeAll': 'Tümü',
      'allergies': 'Alerjiler',
      'conditions': 'Durumlar',
      'emergencyTitle': 'Acil durum mu? 112’yi arayın',
      'emergencySubtitle':
          'Hayati tehlike olan durumlarda her zaman acil hizmetleri arayın.',
      'noRecentActivity': 'Henüz etkinlik yok.',
      'noRecentActivitySubtitle':
          'Geçmişinizi oluşturmak için belirti kontrolü yapın veya ilaçları inceleyin.',
      'completeProfileTitle': 'Sağlık profilinizi tamamlayın',
      'completeProfileSubtitle':
          'Uygulamanın size özel öneriler vermesi için temel bilgileri bir kez ekleyin.',
      'chooseAvatar': 'Avatar seçin',
      'bloodType': 'Kan Grubu',
      'weightKg': 'Kilo (kg)',
      'heightCm': 'Boy (cm)',
      'continueToApp': 'Panoya devam et',
      'profileSetupHint':
          'Bu bilgileri daha sonra profil ekranından düzenleyebilirsiniz.',
      'personalInformation': 'Kişisel Bilgiler',
      'editing': 'Düzenleniyor',
      'name': 'Ad',
      'weight': 'Kilo',
      'height': 'Boy',
      'notSet': 'Belirtilmedi',
      'myAllergies': 'Alerjilerim',
      'myConditions': 'Durumlarım',
      'addAllergy': 'Alerji Ekle',
      'addCondition': 'Durum Ekle',
      'noAllergies':
          'Henüz kayıtlı alerji yok. İlaç güvenliği için bir tane ekleyin.',
      'noConditions':
          'Henüz kayıtlı durum yok. Önerileri kişiselleştirmek için ekleyin.',
      'settings': 'Ayarlar',
      'theme': 'Tema',
      'language': 'Dil',
      'light': 'Açık',
      'dark': 'Koyu',
      'system': 'Sistem',
      'english': 'İngilizce',
      'russian': 'Rusça',
      'kazakh': 'Kazakça',
      'turkish': 'Türkçe',
      'emailNotVerified': 'Email henüz doğrulanmadı',
      'resendVerification': 'Doğrulama emailini tekrar gönder',
      'signOut': 'Çıkış Yap',
      'symptomChecker': 'Belirti Kontrolü',
      'aiSymptomAnalysis': 'AI Belirti Analizi',
      'symptomAnalysisSubtitle':
          'Aşağıya belirtilerinizi ekleyin ve uygulama olası durumları değerlendirsin.',
      'addSymptoms': 'Belirti Ekle',
      'typeSymptom': 'Bir belirti yazın...',
      'commonSymptoms': 'Yaygın Belirtiler',
      'selected': 'Seçilen ({count})',
      'analyzeSymptoms': 'Belirtileri Analiz Et',
      'analyzing': 'Analiz ediliyor...',
      'addAtLeastOneSymptom': 'Lütfen en az bir belirti ekleyin.',
      'medicalDisclaimer':
          'Bu araç yalnızca bilgilendirme amaçlıdır ve doktor tavsiyesinin yerini tutmaz.',
      'analyzingSymptomsTitle': 'Belirtileriniz analiz ediliyor...',
      'aiProcessingCount': 'AI {count} belirtiyi işliyor.',
      'matchingPatterns': 'Belirti kalıpları eşleştiriliyor...',
      'evaluatingSeverity': 'Şiddet değerlendiriliyor...',
      'generatingRecommendations': 'Öneriler hazırlanıyor...',
      'severity': 'Şiddet',
      'possibleConditions': 'Olası Durumlar',
      'matchPercent': '%{count} eşleşme',
      'recommendedActions': 'Önerilen Adımlar',
      'consultDoctor':
          'Belirtilerinize göre lütfen mümkün olan en kısa sürede doktora başvurun.',
      'medicineGuide': 'İlaç Rehberi',
      'searchMedicines': 'İlaç ara...',
      'medicineHeroTitle': 'Tam rehberi açmak için bir ilaca dokunun',
      'medicineHeroSubtitle':
          'Doz, uyarılar, yan etkiler ve saklama bilgilerini görün, önemli ilaçları kaydedin.',
      'noMedicinesFound': 'İlaç bulunamadı',
      'noMedicinesFoundSubtitle':
          'Farklı bir arama terimi veya kategori deneyin.',
      'savedMedicines': 'Kaydedilen ilaçlar',
      'medicineViewed': 'İlaç görüntülendi',
      'tapToOpenFullGuide': 'Tam rehberi açmak için dokunun',
      'prescriptionRequired': 'Reçete gerekli',
      'nonPrescription': 'Reçetesiz',
      'allergyWarning': 'Alerji Uyarısı',
      'allergyWarningSubtitle':
          'Bu ilaç profilinizle eşleşen alerjenler içerebilir:',
      'consultBeforeMedication':
          'Lütfen bu ilacı almadan önce doktorunuza danışın.',
      'description': 'Açıklama',
      'usageIndication': 'Kullanım ve endikasyonlar',
      'howToUse': 'Nasıl Kullanılır',
      'dosage': 'Dozaj',
      'warnings': 'Uyarılar',
      'sideEffects': 'Yan Etkiler',
      'ingredients': 'İçerikler',
      'knownAllergens': 'Bilinen Alerjenler',
      'contraindications': 'Kontrendikasyonlar',
      'interactions': 'Etkileşimler',
      'storageInstructions': 'Saklama talimatları',
      'pregnancyBreastfeeding': 'Hamilelik ve emzirme',
      'whenToSeeDoctor': 'Ne zaman doktora görünmeli',
      'emergencyWarning': 'Acil uyarı',
      'manufacturedBy': 'Üretici',
      'saveMedicine': 'İlacı kaydet',
      'removeSavedMedicineCta': 'Kaydedilenden kaldır',
      'shareMedicine': 'Paylaş',
      'medicineSavedForLater': 'İlaç hızlı erişim için kaydedildi.',
      'medicineRemovedFromSaved': 'İlaç kaydedilenlerden kaldırıldı.',
      'medicineCopiedForSharing':
          'İlaç özeti panoya kopyalandı. İstediğiniz yerde paylaşabilirsiniz.',
      'medicalEducationDisclaimer':
          'Bu bilgiler yalnızca eğitim amaçlıdır ve profesyonel tıbbi tavsiyenin yerini tutmaz.',
      'nearbyMedicalHelp': 'Yakındaki Tıbbi Yardım',
      'findingNearby': 'Yakınınızdaki yerler bulunuyor...',
      'medicalMapTitle': 'Tıbbi harita',
      'medicalPlacesNearYou': 'Yakınınızdaki tıbbi yerler',
      'loadingNearbyPlacesSubtitle':
          'Hastaneler, klinikler, eczaneler ve acil bakım yükleniyor...',
      'all': 'Tümü',
      'hospital': 'Hastane',
      'clinic': 'Klinik',
      'pharmacy': 'Eczane',
      'emergency': 'Acil',
      'selectedLabel': 'Seçildi',
      'openNow': 'Açık',
      'openShort': 'Açık',
      'closed': 'Kapalı',
      'waitTime': 'Bekleme süresi',
      'placesFound': '{count} yer bulundu',
      'nearbyPlacesReady': 'Hazır yer sayısı: {count}',
      'resultsCount': '{count} sonuç',
      'gpsActive': 'GPS aktif',
      'call': 'Ara',
      'directions': 'Yol tarifi',
      'listView': 'Liste',
      'mapView': 'Harita',
      'routeOff': 'Rota kapalı',
      'routeActive': 'Rota aktif',
      'nearest': 'En yakın',
      'topRated': 'En yüksek puan',
      'ratingLabel': 'Puan',
      'sortPlaces': 'Yerleri sırala',
      'sortByNearest': 'En yakına göre sırala',
      'sortByRating': 'Puana göre sırala',
      'sortByOpenNow': 'Şu an açık olana göre sırala',
      'sortNearestLabel': 'Önce en yakın',
      'waitPrefix': 'Bekleme: {time}',
      'unableToOpenLink': 'Bu işlem cihazınızda açılamadı.',
      'routeDirectionsUnavailable': 'Yol tarifi şu anda kullanılamıyor.',
      'routeUnavailableLabel': 'Kullanılamıyor',
      'hospitalRouteStarted': 'Hastane rotası başlatıldı',
      'nearbyNoPlacesAround': 'Konumunuzun yakınında tıbbi yer bulunamadı.',
      'nearbySearchEmpty': 'Aramanızla eşleşen hastane bulunamadı.',
      'nearbySearchFailed': 'Arama başarısız oldu. Başka bir sorgu deneyin.',
      'nearbyApiFailure':
          'Canlı yerler yüklenemedi. Ağınızı veya API kurulumunu kontrol edin.',
      'nearbyFallbackShown':
          'Canlı veriler kullanılamadığı için demo ve kaydedilen tıbbi yerler gösteriliyor.',
      'transportModes': 'Ulaşım modları',
      'hospitalDetails': 'Hastane ayrıntıları',
      'addressLabel': 'Adres',
      'phoneLabel': 'Telefon',
      'websiteLabel': 'Web sitesi',
      'removeActivity': 'Etkinliği kaldır',
      'activityRemoved': 'Etkinlik kaldırıldı.',
      'searchNearbyHint': 'Yakındaki hastane, klinik, eczane ara...',
      'savedPlaces': 'Kaydedilen Yerler',
      'noSavedPlaces': 'Henüz kaydedilen yer yok.',
      'noSavedPlacesSubtitle':
          'Daha sonra hızlı erişim için faydalı hastane, klinik ve eczaneleri kaydedin.',
      'recentSearches': 'Son Aramalar',
      'noRecentSearches': 'Henüz son arama yok.',
      'routeOptions': 'Rota Seçenekleri',
      'walking': 'Yürüyüş',
      'driving': 'Araba',
      'publicTransport': 'Toplu taşıma',
      'scooter': 'Scooter',
      'openWebsite': 'Siteyi Aç',
      'savePlace': 'Yeri Kaydet',
      'removeSavedPlace': 'Kayıttan Kaldır',
      'placeSaved': 'Yer kaydedildi.',
      'placeRemoved': 'Yer kaldırıldı.',
      'distance': 'Mesafe',
      'coordinates': 'Koordinatlar',
      'startNavigation': 'Navigasyonu Başlat',
      'routeUnavailable': 'Bu mod için uygulama içi rota kullanılamıyor.',
      'openInMaps': 'Maps\'ta Aç',
      'currentLocation': 'Mevcut konum',
      'locationServicesDisabled':
          'Yakındaki yardımı bulmak için konum servislerini açın.',
      'locationPermissionDenied':
          'Yakındaki hastaneleri ve rotaları göstermek için konum izni gerekiyor.',
      'locationPermissionDeniedForever':
          'Konum izni kalıcı olarak reddedildi. Devam etmek için ayarları açın.',
      'openSettings': 'Ayarları Aç',
      'enableLocation': 'Konumu Aç',
      'retry': 'Tekrar Dene',
      'findingYourLocation': 'Konumunuz bulunuyor...',
      'searchResults': 'Arama Sonuçları',
      'noPlacesFound': 'Yer bulunamadı',
      'noPlacesFoundSubtitle':
          'Farklı bir arama deneyin veya sağlık kategorisini değiştirin.',
      'loadingRoute': 'Rota hesaplanıyor...',
      'clearRecentSearches': 'Son Aramaları Temizle',
      'searchNearbyHospitals': 'Yakındaki Hastaneleri Ara',
      'clearHealthData': 'Sağlık verilerini temizle',
      'clearHealthDataSubtitle':
          'Alerjileri, durumları, ölçümleri ve son etkinlikleri profilinizden kaldırmak istiyor musunuz?',
      'healthDataCleared': 'Sağlık verileri temizlendi.',
      'confirm': 'Onayla',
      'checkups': 'Kontroller',
      'now': 'Şimdi',
      'minutesAgo': '{count} dk önce',
      'hoursAgo': '{count} sa önce',
      'daysAgo': '{count} g önce',
      'onboardingFeatureAnalysis': 'AI destekli analiz',
      'onboardingFeatureSeverity': 'Şiddet değerlendirmesi',
      'onboardingFeatureGuidance': 'Tedavi yönlendirmesi',
      'onboardingFeatureSafety': 'İlaç güvenliği kontrolleri',
      'onboardingFeatureWarnings': 'Alerjiye duyarlı uyarılar',
      'onboardingFeatureDosing': 'Doz bilgileri',
      'onboardingFeatureClinics': 'Klinikler ve hastaneler',
      'onboardingFeaturePharmacies': 'Yakındaki eczaneler',
      'onboardingFeatureContacts': 'Acil durum kişileri',
      'onboardingTitle1': 'AI sağlık yardımcınız',
      'onboardingSubtitle1':
          'MediGuide AI belirtileri, ilaçları ve bakım seçeneklerini tek yerde toplar.',
      'onboardingTitle2': 'Akıllı belirti analizi',
      'onboardingSubtitle2':
          'Belirtileri kontrol edin, riski değerlendirin ve sonraki adımı görün.',
      'onboardingTitle3': 'İlaç güvenliği ve alerjiler',
      'onboardingSubtitle3':
          'İlacı almadan önce alerji profilinizle karşılaştırın.',
      'onboardingTitle4': 'Yakın yardımı bulun',
      'onboardingSubtitle4':
          'Yakındaki klinikleri, hastaneleri, eczaneleri ve acil noktaları görüntüleyin.',
      'greetingMorning': 'Günaydın',
      'greetingAfternoon': 'Tünaydın',
      'greetingEvening': 'İyi akşamlar',
      'greetingNight': 'İyi geceler',
    },
  };

  static const Map<String, Map<String, String>> _dynamicStrings = {
    'ru': {
      'General Discomfort': 'Общее недомогание',
      'Tension Headache': 'Головная боль напряжения',
      'Migraine': 'Мигрень',
      'Dehydration': 'Обезвоживание',
      'Common Cold': 'Простуда',
      'Flu (Influenza)': 'Грипп',
      'COVID-19': 'COVID-19',
      'Gastroenteritis': 'Гастроэнтерит',
      'Angina': 'Стенокардия',
      'Asthma': 'Астма',
      'Allergic Reaction': 'Аллергическая реакция',
      'Low': 'Низкая',
      'Medium': 'Средняя',
      'High': 'Высокая',
      'Unknown': 'Неизвестно',
      'A viral infection of the upper respiratory tract causing runny nose, sore throat, and cough.':
          'Вирусная инфекция верхних дыхательных путей, вызывающая насморк, боль в горле и кашель.',
      'A contagious respiratory illness caused by influenza viruses affecting the nose, throat, and lungs.':
          'Заразное респираторное заболевание, вызванное вирусами гриппа и поражающее нос, горло и лёгкие.',
      'Coronavirus disease caused by SARS-CoV-2, ranging from mild to severe respiratory illness.':
          'Коронавирусное заболевание, вызванное SARS-CoV-2, от лёгкой до тяжёлой респираторной формы.',
      'Your symptoms may indicate a minor ailment. Monitor your condition and consult a doctor if symptoms persist.':
          'Ваши симптомы могут указывать на лёгкое недомогание. Наблюдайте за состоянием и обратитесь к врачу, если симптомы сохраняются.',
      'Please consult a healthcare professional as soon as possible.':
          'Пожалуйста, как можно скорее обратитесь к медицинскому специалисту.',
      'Analgesic': 'Обезболивающее',
      'Antibiotic': 'Антибиотик',
      'Antihistamine': 'Антигистаминное',
      'NSAID': 'НПВП',
      'Antidiabetic': 'Противодиабетическое',
      'Proton Pump': 'Ингибитор протонной помпы',
      'Lifestyle': 'Образ жизни',
      'Exercise': 'Физическая активность',
      'Sleep': 'Сон',
      'Nutrition': 'Питание',
      'Mental Health': 'Психическое здоровье',
      'Prevention': 'Профилактика',
      'Stay Hydrated': 'Поддерживайте водный баланс',
      'Drink at least 8 glasses of water daily to maintain optimal body function.':
          'Пейте не менее 8 стаканов воды в день, чтобы поддерживать нормальную работу организма.',
      'Move More': 'Больше двигайтесь',
      '30 minutes of moderate exercise daily can reduce cardiovascular disease risk by 35%.':
          '30 минут умеренной активности в день могут снизить риск сердечно-сосудистых заболеваний на 35%.',
      'Quality Sleep': 'Качественный сон',
      'Adults need 7-9 hours of sleep. Poor sleep is linked to diabetes, obesity, and heart disease.':
          'Взрослым нужно 7-9 часов сна. Недостаток сна связан с диабетом, ожирением и сердечными заболеваниями.',
      'Eat the Rainbow': 'Ешьте разнообразные овощи и фрукты',
      'Include colorful fruits and vegetables in your diet for diverse nutrients and antioxidants.':
          'Добавляйте в рацион разноцветные овощи и фрукты для получения разных питательных веществ и антиоксидантов.',
      'Manage Stress': 'Управляйте стрессом',
      'Chronic stress weakens immunity. Try meditation, yoga, or deep breathing for 10 minutes daily.':
          'Хронический стресс ослабляет иммунитет. Попробуйте медитацию, йогу или глубокое дыхание по 10 минут в день.',
      'Regular Checkups': 'Регулярные осмотры',
      'Annual health screenings can detect issues early. Prevention is always better than treatment.':
          'Ежегодные обследования помогают выявить проблемы заранее. Профилактика всегда лучше лечения.',
      'City Medical Center': 'Городской медицинский центр',
      '123 Health Blvd, Central District': 'бул. Health 123, Центральный район',
      'MedCare Pharmacy': 'Аптека MedCare',
      '45 Oak Street, Downtown': 'ул. Oak 45, центр города',
      'Family Health Clinic': 'Семейная клиника здоровья',
      '78 Maple Avenue, East Side': 'пр. Maple 78, восточная часть',
      'QuickCare Pharmacy': 'Аптека QuickCare',
      '200 Park Road, West End': 'Park Road 200, западный район',
      'Downtown Emergency Center': 'Центр неотложной помощи',
      '1 Emergency Lane, City Center': 'Emergency Lane 1, центр города',
      'Specialist Medical Clinic': 'Клиника профильных специалистов',
      '55 Wellness Drive, North Quarter': 'Wellness Drive 55, северный квартал',
      'HealthPlus Hospital': 'Больница HealthPlus',
      '500 Medical Campus Dr, East District':
          'Medical Campus Dr 500, восточный район',
      '24/7 Emergency': 'Круглосуточно, экстренная помощь',
      '8 AM – 10 PM': '08:00 – 22:00',
      '9 AM – 6 PM': '09:00 – 18:00',
      '7 AM – 11 PM': '07:00 – 23:00',
      '24/7': 'Круглосуточно',
      '9 AM – 5 PM (Mon–Fri)': '09:00 – 17:00 (пн–пт)',
      'Activity': 'Активность',
      'nearby clinics': 'клиники рядом',
      'nearby pharmacies': 'аптеки рядом',
      'nearby emergency hospitals': 'ближайшие экстренные больницы',
      'nearby hospitals clinics pharmacies': 'больницы, клиники и аптеки рядом',
      'Walking directions may include paths with limited accessibility.':
          'Пеший маршрут может проходить по участкам с ограниченной доступностью.',
      'Scooter routing availability depends on region and may follow two-wheeler roads.':
          'Доступность маршрута для скутера зависит от региона и может использовать дороги для двухколёсного транспорта.',
      'Scooter routing is unavailable in this region. Showing driving route as fallback.':
          'Маршрут для скутера недоступен в этом регионе. Показан автомобильный маршрут как запасной вариант.',
    },
    'kk': {
      'General Discomfort': 'Жалпы жайсыздық',
      'Tension Headache': 'Кернеу бас ауруы',
      'Migraine': 'Мигрень',
      'Dehydration': 'Сусыздану',
      'Common Cold': 'Тұмау тию',
      'Flu (Influenza)': 'Тұмау',
      'COVID-19': 'COVID-19',
      'Gastroenteritis': 'Гастроэнтерит',
      'Angina': 'Стенокардия',
      'Asthma': 'Астма',
      'Allergic Reaction': 'Аллергиялық реакция',
      'Low': 'Төмен',
      'Medium': 'Орташа',
      'High': 'Жоғары',
      'Unknown': 'Белгісіз',
      'A viral infection of the upper respiratory tract causing runny nose, sore throat, and cough.':
          'Мұрын ағу, тамақ ауруы және жөтел тудыратын жоғарғы тыныс жолдарының вирустық инфекциясы.',
      'A contagious respiratory illness caused by influenza viruses affecting the nose, throat, and lungs.':
          'Мұрынға, тамаққа және өкпеге әсер ететін тұмау вирустарынан туындайтын жұқпалы тыныс алу ауруы.',
      'Coronavirus disease caused by SARS-CoV-2, ranging from mild to severe respiratory illness.':
          'SARS-CoV-2 вирусынан туындайтын, жеңілден ауыр түрге дейін баратын респираторлық ауру.',
      'Your symptoms may indicate a minor ailment. Monitor your condition and consult a doctor if symptoms persist.':
          'Симптомдарыңыз жеңіл сырқатты білдіруі мүмкін. Жағдайыңызды бақылап, симптомдар сақталса дәрігерге көрініңіз.',
      'Please consult a healthcare professional as soon as possible.':
          'Мүмкіндігінше тезірек медицина маманына жүгініңіз.',
      'Analgesic': 'Ауырсынуды басатын',
      'Antibiotic': 'Антибиотик',
      'Antihistamine': 'Антигистамин',
      'NSAID': 'ҚҚСП',
      'Antidiabetic': 'Диабетке қарсы',
      'Proton Pump': 'Протон помпасы ингибиторы',
      'Lifestyle': 'Өмір салты',
      'Exercise': 'Жаттығу',
      'Sleep': 'Ұйқы',
      'Nutrition': 'Тамақтану',
      'Mental Health': 'Психикалық денсаулық',
      'Prevention': 'Алдын алу',
      'Stay Hydrated': 'Суды жеткілікті ішіңіз',
      'Drink at least 8 glasses of water daily to maintain optimal body function.':
          'Ағзаның дұрыс жұмыс істеуі үшін күніне кемінде 8 стақан су ішіңіз.',
      'Move More': 'Көбірек қозғалыңыз',
      '30 minutes of moderate exercise daily can reduce cardiovascular disease risk by 35%.':
          'Күніне 30 минут орташа жаттығу жүрек-қан тамыр аурулары қаупін 35%-ға азайтуы мүмкін.',
      'Quality Sleep': 'Сапалы ұйқы',
      'Adults need 7-9 hours of sleep. Poor sleep is linked to diabetes, obesity, and heart disease.':
          'Ересектерге 7-9 сағат ұйқы керек. Ұйқының аздығы диабет, семіздік және жүрек ауруларымен байланысты.',
      'Eat the Rainbow': 'Түрлі түсті тағам жеңіз',
      'Include colorful fruits and vegetables in your diet for diverse nutrients and antioxidants.':
          'Әртүрлі қоректік заттар мен антиоксиданттар үшін рационыңызға түрлі түсті жеміс-жидек пен көкөніс қосыңыз.',
      'Manage Stress': 'Стресті басқарыңыз',
      'Chronic stress weakens immunity. Try meditation, yoga, or deep breathing for 10 minutes daily.':
          'Созылмалы стресс иммунитетті әлсіретеді. Күніне 10 минут медитация, йога немесе терең тыныс алуды байқап көріңіз.',
      'Regular Checkups': 'Тұрақты тексерулер',
      'Annual health screenings can detect issues early. Prevention is always better than treatment.':
          'Жыл сайынғы тексерулер мәселені ерте анықтауға көмектеседі. Алдын алу әрқашан емдеуден жақсы.',
      'City Medical Center': 'Қалалық медициналық орталық',
      '123 Health Blvd, Central District': 'Health Blvd 123, Орталық аудан',
      'MedCare Pharmacy': 'MedCare дәріханасы',
      '45 Oak Street, Downtown': 'Oak Street 45, қала орталығы',
      'Family Health Clinic': 'Отбасылық денсаулық клиникасы',
      '78 Maple Avenue, East Side': 'Maple Avenue 78, шығыс бөлік',
      'QuickCare Pharmacy': 'QuickCare дәріханасы',
      '200 Park Road, West End': 'Park Road 200, батыс бөлік',
      'Downtown Emergency Center': 'Қалалық жедел көмек орталығы',
      '1 Emergency Lane, City Center': 'Emergency Lane 1, қала орталығы',
      'Specialist Medical Clinic': 'Мамандандырылған медициналық клиника',
      '55 Wellness Drive, North Quarter':
          'Wellness Drive 55, солтүстік квартал',
      'HealthPlus Hospital': 'HealthPlus ауруханасы',
      '500 Medical Campus Dr, East District':
          'Medical Campus Dr 500, шығыс аудан',
      '24/7 Emergency': 'Тәулік бойы шұғыл көмек',
      '8 AM – 10 PM': '08:00 – 22:00',
      '9 AM – 6 PM': '09:00 – 18:00',
      '7 AM – 11 PM': '07:00 – 23:00',
      '24/7': 'Тәулік бойы',
      '9 AM – 5 PM (Mon–Fri)': '09:00 – 17:00 (дс–жм)',
      'Activity': 'Белсенділік',
      'nearby clinics': 'жақын клиникалар',
      'nearby pharmacies': 'жақын дәріханалар',
      'nearby emergency hospitals': 'жақын жедел ауруханалар',
      'nearby hospitals clinics pharmacies':
          'жақын аурухана, клиника және дәріхана',
      'Walking directions may include paths with limited accessibility.':
          'Жаяу маршрут қолжетімділігі шектеулі жолдарды қамтуы мүмкін.',
      'Scooter routing availability depends on region and may follow two-wheeler roads.':
          'Скутер маршрутының қолжетімділігі аймаққа байланысты және екі дөңгелекті жолдарды қолдануы мүмкін.',
      'Scooter routing is unavailable in this region. Showing driving route as fallback.':
          'Бұл аймақта скутер маршруты қолжетімсіз. Қосымша ретінде көлік маршруты көрсетілді.',
    },
    'tr': {
      'General Discomfort': 'Genel Rahatsızlık',
      'Tension Headache': 'Gerilim Tipi Baş Ağrısı',
      'Migraine': 'Migren',
      'Dehydration': 'Susuzluk',
      'Common Cold': 'Soğuk Algınlığı',
      'Flu (Influenza)': 'Grip',
      'COVID-19': 'COVID-19',
      'Gastroenteritis': 'Gastroenterit',
      'Angina': 'Anjina',
      'Asthma': 'Astım',
      'Allergic Reaction': 'Alerjik Reaksiyon',
      'Low': 'Düşük',
      'Medium': 'Orta',
      'High': 'Yüksek',
      'Unknown': 'Bilinmiyor',
      'A viral infection of the upper respiratory tract causing runny nose, sore throat, and cough.':
          'Burun akıntısı, boğaz ağrısı ve öksürüğe neden olan üst solunum yolu viral enfeksiyonu.',
      'A contagious respiratory illness caused by influenza viruses affecting the nose, throat, and lungs.':
          'Burun, boğaz ve akciğerleri etkileyen influenza virüslerinin neden olduğu bulaşıcı solunum hastalığı.',
      'Coronavirus disease caused by SARS-CoV-2, ranging from mild to severe respiratory illness.':
          'SARS-CoV-2 kaynaklı, hafiften ağıra değişebilen solunum yolu hastalığı.',
      'Your symptoms may indicate a minor ailment. Monitor your condition and consult a doctor if symptoms persist.':
          'Belirtileriniz hafif bir rahatsızlığa işaret edebilir. Durumunuzu izleyin ve belirtiler devam ederse doktora başvurun.',
      'Please consult a healthcare professional as soon as possible.':
          'Lütfen en kısa sürede bir sağlık uzmanına danışın.',
      'Analgesic': 'Ağrı kesici',
      'Antibiotic': 'Antibiyotik',
      'Antihistamine': 'Antihistaminik',
      'NSAID': 'NSAID',
      'Antidiabetic': 'Diyabet ilacı',
      'Proton Pump': 'Proton pompası',
      'Lifestyle': 'Yaşam tarzı',
      'Exercise': 'Egzersiz',
      'Sleep': 'Uyku',
      'Nutrition': 'Beslenme',
      'Mental Health': 'Ruh sağlığı',
      'Prevention': 'Önleme',
      'Stay Hydrated': 'Su tüketimini artırın',
      'Drink at least 8 glasses of water daily to maintain optimal body function.':
          'Vücudunuzun düzgün çalışması için günde en az 8 bardak su için.',
      'Move More': 'Daha fazla hareket edin',
      '30 minutes of moderate exercise daily can reduce cardiovascular disease risk by 35%.':
          'Günde 30 dakika orta düzey egzersiz, kalp-damar hastalığı riskini %35 azaltabilir.',
      'Quality Sleep': 'Kaliteli uyku',
      'Adults need 7-9 hours of sleep. Poor sleep is linked to diabetes, obesity, and heart disease.':
          'Yetişkinlerin 7-9 saat uykuya ihtiyacı vardır. Yetersiz uyku diyabet, obezite ve kalp hastalıkları ile ilişkilidir.',
      'Eat the Rainbow': 'Renkli beslenin',
      'Include colorful fruits and vegetables in your diet for diverse nutrients and antioxidants.':
          'Farklı besinler ve antioksidanlar için beslenmenize renkli meyve ve sebzeler ekleyin.',
      'Manage Stress': 'Stresi yönetin',
      'Chronic stress weakens immunity. Try meditation, yoga, or deep breathing for 10 minutes daily.':
          'Kronik stres bağışıklığı zayıflatır. Günde 10 dakika meditasyon, yoga veya derin nefes deneyin.',
      'Regular Checkups': 'Düzenli kontroller',
      'Annual health screenings can detect issues early. Prevention is always better than treatment.':
          'Yıllık sağlık kontrolleri sorunları erken tespit edebilir. Önlem almak her zaman tedaviden iyidir.',
      'City Medical Center': 'Şehir Tıp Merkezi',
      '123 Health Blvd, Central District': '123 Health Blvd, Merkez Bölge',
      'MedCare Pharmacy': 'MedCare Eczanesi',
      '45 Oak Street, Downtown': '45 Oak Street, şehir merkezi',
      'Family Health Clinic': 'Aile Sağlık Kliniği',
      '78 Maple Avenue, East Side': '78 Maple Avenue, doğu tarafı',
      'QuickCare Pharmacy': 'QuickCare Eczanesi',
      '200 Park Road, West End': '200 Park Road, batı yakası',
      'Downtown Emergency Center': 'Merkez Acil Yardım Merkezi',
      '1 Emergency Lane, City Center': '1 Emergency Lane, şehir merkezi',
      'Specialist Medical Clinic': 'Uzmanlık Tıp Kliniği',
      '55 Wellness Drive, North Quarter': '55 Wellness Drive, kuzey bölgesi',
      'HealthPlus Hospital': 'HealthPlus Hastanesi',
      '500 Medical Campus Dr, East District':
          '500 Medical Campus Dr, doğu bölgesi',
      '24/7 Emergency': '7/24 Acil',
      '8 AM – 10 PM': '08:00 – 22:00',
      '9 AM – 6 PM': '09:00 – 18:00',
      '7 AM – 11 PM': '07:00 – 23:00',
      '24/7': '7/24',
      '9 AM – 5 PM (Mon–Fri)': '09:00 – 17:00 (Pzt–Cum)',
      'Activity': 'Etkinlik',
      'nearby clinics': 'yakındaki klinikler',
      'nearby pharmacies': 'yakındaki eczaneler',
      'nearby emergency hospitals': 'yakındaki acil hastaneler',
      'nearby hospitals clinics pharmacies':
          'yakındaki hastane, klinik ve eczaneler',
      'Walking directions may include paths with limited accessibility.':
          'Yürüyüş rotası sınırlı erişilebilirliğe sahip yollar içerebilir.',
      'Scooter routing availability depends on region and may follow two-wheeler roads.':
          'Scooter rota kullanılabilirliği bölgeye bağlıdır ve iki tekerlekli yolları takip edebilir.',
      'Scooter routing is unavailable in this region. Showing driving route as fallback.':
          'Scooter rotası bu bölgede kullanılamıyor. Yedek olarak araba rotası gösteriliyor.',
    },
  };

  static const Map<String, Map<String, String>> _symptomLabels = {
    'Headache': {
      'ru': 'Головная боль',
      'kk': 'Бас ауруы',
      'tr': 'Baş ağrısı',
    },
    'Fever': {
      'ru': 'Температура',
      'kk': 'Қызу',
      'tr': 'Ateş',
    },
    'Cough': {
      'ru': 'Кашель',
      'kk': 'Жөтел',
      'tr': 'Öksürük',
    },
    'Sore throat': {
      'ru': 'Боль в горле',
      'kk': 'Тамақ ауруы',
      'tr': 'Boğaz ağrısı',
    },
    'Fatigue': {
      'ru': 'Усталость',
      'kk': 'Шаршау',
      'tr': 'Yorgunluk',
    },
    'Nausea': {
      'ru': 'Тошнота',
      'kk': 'Жүрек айну',
      'tr': 'Mide bulantısı',
    },
    'Dizziness': {
      'ru': 'Головокружение',
      'kk': 'Бас айналу',
      'tr': 'Baş dönmesi',
    },
    'Runny nose': {
      'ru': 'Насморк',
      'kk': 'Мұрын ағу',
      'tr': 'Burun akıntısı',
    },
    'Back pain': {
      'ru': 'Боль в спине',
      'kk': 'Арқа ауруы',
      'tr': 'Sırt ağrısı',
    },
    'Chest pain': {
      'ru': 'Кеуде ауыруы',
      'kk': 'Кеуде ауруы',
      'tr': 'Göğüs ağrısı',
    },
    'Shortness of breath': {
      'ru': 'Одышка',
      'kk': 'Демігу',
      'tr': 'Nefes darlığı',
    },
    'Rash': {
      'ru': 'Сыпь',
      'kk': 'Бөртпе',
      'tr': 'Döküntü',
    },
    'Vomiting': {
      'ru': 'Рвота',
      'kk': 'Құсу',
      'tr': 'Kusma',
    },
    'Diarrhea': {
      'ru': 'Диарея',
      'kk': 'Іш өту',
      'tr': 'İshal',
    },
    'Joint pain': {
      'ru': 'Боль в суставах',
      'kk': 'Буын ауруы',
      'tr': 'Eklem ağrısı',
    },
    'Eye pain': {
      'ru': 'Боль в глазах',
      'kk': 'Көз ауруы',
      'tr': 'Göz ağrısı',
    },
  };

  static String translate(
    String localeCode,
    String key, {
    Map<String, String> params = const {},
  }) {
    final language = _strings[localeCode] ?? _strings[fallbackLocale]!;
    var value = language[key] ?? _strings[fallbackLocale]![key] ?? key;

    for (final entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }

    return value;
  }

  static String translateDynamic(String localeCode, String source) {
    if (localeCode == fallbackLocale) return source;
    return _dynamicStrings[localeCode]?[source] ?? source;
  }

  static String symptomLabel(String localeCode, String symptom) {
    if (localeCode == fallbackLocale) return symptom;
    return _symptomLabels[symptom]?[localeCode] ?? symptom;
  }

  static String canonicalSymptom(String input) {
    final normalized = input.trim().toLowerCase();
    if (normalized.isEmpty) return input.trim();

    for (final entry in _symptomLabels.entries) {
      if (entry.key.toLowerCase() == normalized) {
        return entry.key;
      }
      for (final localized in entry.value.values) {
        if (localized.toLowerCase() == normalized) {
          return entry.key;
        }
      }
    }

    return input.trim();
  }

  static String greetingForTime(String localeCode, DateTime now) {
    if (now.hour < 12) {
      return translate(localeCode, 'greetingMorning');
    }
    if (now.hour < 17) {
      return translate(localeCode, 'greetingAfternoon');
    }
    if (now.hour < 22) {
      return translate(localeCode, 'greetingEvening');
    }
    return translate(localeCode, 'greetingNight');
  }
}

extension AppLocalizationContext on BuildContext {
  String tr(String key, {Map<String, String> params = const {}}) {
    final localeCode = watch<AppPreferencesProvider>().localeCode;
    return AppLocalizations.translate(localeCode, key, params: params);
  }

  String dynamicText(String source) {
    final localeCode = watch<AppPreferencesProvider>().localeCode;
    return AppLocalizations.translateDynamic(localeCode, source);
  }

  String symptomLabel(String source) {
    final localeCode = watch<AppPreferencesProvider>().localeCode;
    return AppLocalizations.symptomLabel(localeCode, source);
  }

  String greeting() {
    final localeCode = watch<AppPreferencesProvider>().localeCode;
    return AppLocalizations.greetingForTime(localeCode, DateTime.now());
  }
}
